[package]
name = "auto-test-scoring"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"

csv = "1.3.1"
walkdir = "2.5.0"
anyhow = "1.0.98"
